[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build --workspace=apps/backend"

[deploy]
startCommand = "npm run start --workspace=apps/backend"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
NIXPACKS_NODE_VERSION = "20"
NIXPACKS_APT_PKGS = "libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 libpango-1.0-0 libcairo2 libx11-6 libxcb1 libxext6"
